// Generated by LiveScript 1.4.0
(function(){
  var gulp, jade, stylus, autoprefixer, nib;
  gulp = require('gulp');
  jade = require('gulp-jade');
  stylus = require('gulp-stylus');
  autoprefixer = require('autoprefixer-stylus');
  nib = require('nib');
  gulp.task('templates', function(){
    return gulp.src('./**/*.jade').pipe(jade({
      pretty: true
    })).pipe(gulp.dest('.'));
  });
  gulp.task('stylus', function(){
    return gulp.src(['./app/styles/stylus/app.styl']).pipe(stylus({
      use: [
        nib(), autoprefixer({
          browsers: ['iOS >= 7', 'Chrome >= 36', 'Firefox >= 30']
        })
      ]
    })).pipe(gulp.dest('./app/dist'));
  });
  gulp.task('watch', function(){
    gulp.watch('./**/*.jade', ['templates']);
    return gulp.watch('./app/styles/**/*.styl', ['stylus']);
  });
  gulp.task('default', ['stylus', 'templates', 'watch']);
}).call(this);
